from django.contrib import admin
from .models import TipoCredito, Documento, FechaClave, Vendedor, Expediente, Cliente, Duplex, Venta, Construccion, Casa, Saldo, ConceptoSaldo, Accesorio, EtapaConstruccion, GradoEstudios, ReferenciaPersonal, Entrega, TipoSeguimiento, Actualizacion
# Register your models here.
admin.site.register(TipoCredito)
admin.site.register(Documento)
admin.site.register(FechaClave)
admin.site.register(Vendedor)
admin.site.register(Expediente)
admin.site.register(Cliente)
admin.site.register(Duplex)
admin.site.register(Venta)
admin.site.register(Construccion)
admin.site.register(Casa)
admin.site.register(Saldo)
admin.site.register(ConceptoSaldo)
admin.site.register(Accesorio)
admin.site.register(EtapaConstruccion)
admin.site.register(GradoEstudios)
admin.site.register(ReferenciaPersonal)
admin.site.register(Entrega)
admin.site.register(TipoSeguimiento)
admin.site.register(Actualizacion)
