# Generated by Django 2.2.5 on 2020-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodoventas', '0005_actualizacion_fecha_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
