# Generated by Django 2.2.5 on 2020-05-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodoventas', '0008_auto_20200511_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entrega',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_por_entrega', to='nodoventas.FechaClave'),
        ),
    ]
