# Generated by Django 2.2.5 on 2020-05-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodoventas', '0009_venta_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='escritura',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_por_escritura', to='nodoventas.Documento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='recibo_apartado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_por_reciboapartado', to='nodoventas.Documento'),
        ),
    ]
