# Generated by Django 2.2.5 on 2020-05-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodoventas', '0010_auto_20200514_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='cliente_cony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casas_por_clientecony', to='nodoventas.Cliente'),
        ),
    ]
